# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 579de70ae4ea9cb002b6ffee6297fa61d24ca1592dd11b294abf50aef04f1bd0bf88c79c1af21d36b9b062b2b3e110f3f6ddfc0c31fabc0eb8b1665fba74627b

test:
  secret_key_base: ba0cf4c5e4540d5b1eebaed76dea93a138c335df4e176b4502f2b1fe8f10341bb1f7c6f3dc6f1012f59940bde75d642b1a298bc88c3ab456fad93671ba07ba1c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
